### ISSUE TITLE
你好，请问最新版本的 tencent-scf.zip在哪呢

### ISSUE THREAD

**Issue by crmsci** [RayWangQvQ/BiliBiliTool.Docs#26]
https://github.com/RayWangQvQ/BiliBiliTool/releases 已经被禁用。
我已经下载这个仓库，https://github.com/RayWangQvQ/BiliBiliTool.Docs/blob/main/tencentScf/README.md的文件，
将bootstrap，index.sh，publish.bat，publish.sh，serverless.yml打包成tencent-scf.zip上传到腾讯云函数中，
按README.md，得到的结果是：
Response: 
{"errorCode":-1,"errorMessage":"ReloadFail: Bootstrap not executable\n","requestId":"9fc18f93-31d5-4c64-ac9c-70d3b48ac6fa","statusCode":443}
Output:

Summary:
  Request ID: 9fc18f93-31d5-4c64-ac9c-70d3b48ac6fa
  Run Duration: 0
  Bill Duration: 0
  Usage Memory: 0
  Invoke Result: -1

**Comment by catlair** [comment]
请下载<https://github.com/RayWangQvQ/BiliBiliTool.Docs/releases>中的 `tencent-scf.zip` 并按照 <https://github.com/RayWangQvQ/BiliBiliTool.Docs/tree/main/tencentScf#32-方式二上传zip包部署> 进行部署

**Comment by RayWangQvQ** [comment]
就在这个仓库的 [Releases](https://github.com/RayWangQvQ/BiliBiliTool.Docs/releases) 里

![image](https://user-images.githubusercontent.com/31154238/119612231-37ddfc00-be2e-11eb-8fef-b2ef0f74c646.png)

**Comment by ascte** [comment]
> 就在这个仓库的 [Releases](https://github.com/RayWangQvQ/BiliBiliTool.Docs/releases) 里
> 
> ![image](https://user-images.githubusercontent.com/31154238/119612231-37ddfc00-be2e-11eb-8fef-b2ef0f74c646.png)

请问大佬，我想从2.01升级到2.02，是不是主需要重新上传下tencent-scf v2.02，其他什么都不用调整对吗？

**Comment by RayWangQvQ** [comment]
> > 就在这个仓库的 [Releases](https://github.com/RayWangQvQ/BiliBiliTool.Docs/releases) 里
> > ![image](https://user-images.githubusercontent.com/31154238/119612231-37ddfc00-be2e-11eb-8fef-b2ef0f74c646.png)
> 
> 请问大佬，我想从2.01升级到2.02，是不是主需要重新上传下tencent-scf v2.02，其他什么都不用调整对吗？

如果配置都是通过环境变量配的，那么是的。
