### ISSUE TITLE
问题如图：

### ISSUE THREAD

**Issue by jizizr** [RayWangQvQ/BiliBiliTool.Docs#27]
bash: Ray.BiliBiliTool.Console: 未找到命令...
![image](https://user-images.githubusercontent.com/78908842/119102444-9a10b880-ba4c-11eb-8cca-211c3b8d0224.png)

**Comment by RayWangQvQ** [comment]
`ls -l`

**Comment by jizizr** [comment]
我忘记加./了不好意思
