### ISSUE TITLE
win-x86-x64 不支持每日自动执行？

### ISSUE THREAD

**Issue by GitHubBean** [RayWangQvQ/BiliBiliTool.Docs#29]
您好，电脑直接win运行：Ray.BiliBiliTool.Console.exe  只能当时执行一次，不能设置成每天凌晨自动执行？
appsettings.json  "RunTasks": "Daily"
请问是有什么特别需要配置的地方么？（参数配置直接修改的配置文件，未添加环境变量），谢谢

**Comment by RayWangQvQ** [comment]
当前应用内部并不包含定时任务，docker 是通过 crontab 、云函数和 github actions 是通过触发器实现的定时任务。

**Comment by mustssr** [comment]
win不就一个计划任务就能解决，还自带随机
