### ISSUE TITLE
GitHub Actions / bilibili-daily-task:Process completed with exit code 134

### ISSUE THREAD

**Issue by lookforhan** [RayWangQvQ/BiliBiliTool.Docs#3]
.github#L1
Process completed with exit code 134.
github action运行错误，错误代码134

**Comment by Raymond-Hear** [comment]
我同样出现了这样的错误，请问这是怎么回事？

**Comment by lookforhan** [comment]
找到解决方法
参考页面[Ubuntu-latest workflows will use Ubuntu-20.04](https://github.com/actions/virtual-environments/issues/1816)

在文件.github/workflows/bilibili-daily-task.yml 中将

`runs-on: ubuntu-latest`

修改为

`runs-on: ubuntu-18.04`

即可

**Comment by lookforhan** [comment]
可以合并该分支

fix issue:GitHub Actions / bilibili-daily-task:Process completed with exit code 134 #3 #183

**Comment by ne7erland** [comment]
更改后还是出现这个错误
.github#L1
Process completed with exit code 134.
