### ISSUE TITLE
安装包无法启动

### ISSUE THREAD

**Issue by sdtime-io** [RayWangQvQ/BiliBiliTool.Docs#41]
[root@iZwz93os69edbarfai8ikrZ bilibili]# ./Ray.BiliBiliTool.Console
-bash: ./Ray.BiliBiliTool.Console: Permission denied

**Comment by sdtime-io** [comment]
![image](https://user-images.githubusercontent.com/10776422/127953348-4b48da20-86b1-4b7d-ba89-94980c6ec5d4.png)

**Comment by CarrotDev-D** [comment]
下载的版本不对

**Comment by RayWangQvQ** [comment]
` dotnet run --project ./Ray.BiliBiliTool.Console`
