### ISSUE TITLE
云函数可以设置多账号吗

### ISSUE THREAD

**Issue by 77uu** [RayWangQvQ/BiliBiliTool.Docs#44]
我像这样写好像不行
environment:
    variables: # 根据自己的需要修改
      Ray_CloseConsoleWhenEnd: 1
      Ray_BiliBiliCookies__1: 123 # cookie，必填
      Ray_BiliBiliCookies__1: 123 # cookie，必填

**Comment by RayWangQvQ** [comment]
Ray_BiliBiliCookies__2
